local base = (import 'base.jsonnet');

base + {
    model+: {
        type: 'gpt_neo',
        config: {
            type: 'gpt_neo',
            activation_function: 'gelu_new',
            architectures: ['GPTNeoForCausalLM'],
            attention_dropout: 0,
            attention_layers: [
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
                'global',
                'local',
            ],
            attention_types: [[['global', 'local'], 6]],
            bos_token_id: 50256,
            embed_dropout: 0,
            eos_token_id: 50256,
            gradient_checkpointing: false,
            hidden_size: 768,
            initializer_range: 0.02,
            intermediate_size: null,
            layer_norm_epsilon: 1e-05,
            max_position_embeddings: 2048,
            model_type: 'gpt_neo',
            num_heads: 12,
            num_layers: 12,
            resid_dropout: 0,
            use_cache: true,
            vocab_size: 50257,
            window_size: 256,
        },
    },
}
